name: Atualizar GitHub Stats

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Baixar estatísticas privadas
        run: |
          curl "https://github-readme-stats-lyart-xi-njmd2xfuoy.vercel.app/api?username=ViniPolonio&show_icons=true&theme=radical&count_private=true" -o stats.svg
          curl "https://github-readme-stats-lyart-xi-njmd2xfuoy.vercel.app/api/top-langs/?username=ViniPolonio&layout=compact&theme=radical&count_private=true" -o langs.svg

      - name: Commit e push das imagens
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats.svg langs.svg
          git commit -m 'Atualiza estatísticas privadas do GitHub' || echo "Nada para commitar"
          git pull --rebase
          git push